#!/usr/bin/env php
<?php
declare(strict_types = 1);
require __DIR__ . '/bootstrap_console.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);